name: Build

on:
  push:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - id: cache
        name: Yarn Cache Dir
        run: echo "value=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Restore Lockfile
        uses: actions/cache@v3
        with:
          path: yarn.lock
          key: yarn-lock-${{ github.sha }}
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache.outputs.value }}
          key: yarn-cache-${{ github.sha }}-node-16
      - name: Install
        run: yarn

    outputs:
      cache-dir: ${{ steps.cache.outputs.value }}

  build:
    runs-on: ubuntu-latest
    needs:
      - prepare

    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore Lockfile
        uses: actions/cache@v3
        with:
          path: yarn.lock
          key: yarn-lock-${{ github.sha }}
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ${{ needs.prepare.outputs.cache-dir }}
          key: yarn-cache-${{ github.sha }}-node-16
      - name: Install
        run: yarn
      - name: Build Clean
        run: yarn build --clean
      - name: Build
        run: yarn build
      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            packages
            plugins

  lint:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs:
      - prepare

    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore Lockfile
        uses: actions/cache@v3
        with:
          path: yarn.lock
          key: yarn-lock-${{ github.sha }}
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ${{ needs.prepare.outputs.cache-dir }}
          key: yarn-cache-${{ github.sha }}-node-16
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint